findByEmail=SELECT * FROM USUARIO WHERE EMAIL = ?1
findByNumeroConta=SELECT * FROM CONTA WHERE NUMERO_CONTA = ?1
findByContaOrigemId=SELECT * FROM AGENDAMENTO WHERE CONTA_ORIGEM = ?1
findByContaDestinoId=SELECT * FROM AGENDAMENTO WHERE CONTA_DESTINO = ?1